create table MEETING (id bigint generated by default as identity (start with 1), endTime timestamp, startTime timestamp, title varchar(128) not null, venue varchar(64) not null, primary key (id));

INSERT INTO MEETING VALUES(1,'2013-01-30 19:00:00.000000','2013-01-30 15:00:00.000000','Knowledge sharing','Cegeka Leuven');

